### ISSUE TITLE
Unexpected token using bulk import

### ISSUE THREAD

**Issue by malderhout** [taskrabbit/elasticsearch-dump#102]
Hello,

I use the following command to import a json file "wijn.json" to ES index "wijn" and get an unexpected token error:

elasticdump --bulk=true --input=wijn.json --output=http://dockerhost:9200/wijn 

Fri, 31 Jul 2015 07:57:02 GMT | starting dump
undefined:1
"Spanje": "Frankrijk",
        ^
SyntaxError: Unexpected token :
    at Object.parse (native)
    at /usr/local/lib/node_modules/elasticdump/lib/transports/file.js:45:27
    at getLine (/usr/local/lib/node_modules/elasticdump/node_modules/line-reader/lib/line_reader.js:74:9)
    at LineReader.nextLine (/usr/local/lib/node_modules/elasticdump/node_modules/line-reader/lib/line_reader.js:93:9)
    at file.getLines (/usr/local/lib/node_modules/elasticdump/lib/transports/file.js:37:17)
    at /usr/local/lib/node_modules/elasticdump/lib/transports/file.js:51:12
    at getLine (/usr/local/lib/node_modules/elasticdump/node_modules/line-reader/lib/line_reader.js:74:9)
    at LineReader.nextLine (/usr/local/lib/node_modules/elasticdump/node_modules/line-reader/lib/line_reader.js:93:9)
    at file.getLines (/usr/local/lib/node_modules/elasticdump/lib/transports/file.js:37:17)
    at /usr/local/lib/node_modules/elasticdump/lib/transports/file.js:51:12

**Comment by evantahler** [comment]
Looks like your file is invalid JSON.
