### ISSUE TITLE
Error Emitted => unknown type option

### ISSUE THREAD

**Issue by Hubbitus** [taskrabbit/elasticsearch-dump#103]
`sudo npm install -g elasticdump`

```
elasticdump \
    --input=http://server1.local:9200/pgstat-2015.08.07 \
    --output=http://server1.local:9200/pgstat-2015.08.07_reindexed \
    --type=all \
    --bulk=true

Mon, 10 Aug 2015 12:00:23 GMT | starting dump
Mon, 10 Aug 2015 12:00:23 GMT | Error Emitted => unknown type option

/usr/lib/node_modules/elasticdump/elasticdump.js:114
      self.log("got " + data.length + " objects from source " + self.inputType
                            ^
TypeError: Cannot read property 'length' of null
    at /usr/lib/node_modules/elasticdump/elasticdump.js:114:29
    at elasticsearch.get (/usr/lib/node_modules/elasticdump/lib/transports/elasticsearch.js:25:9)
    at elasticdump.dump (/usr/lib/node_modules/elasticdump/elasticdump.js:112:16)
    at Object.<anonymous> (/usr/lib/node_modules/elasticdump/bin/elasticdump:67:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

**Comment by evantahler** [comment]
This will fix the stack trace error: https://github.com/taskrabbit/elasticsearch-dump/commit/bb638b3ff032a061232cd93ce3b33ba0c512a4a3

`all` is not a valid type, only `data` or `mapping`

**Comment by Hubbitus** [comment]
Thanks.
