### ISSUE TITLE
Copiying index with "/" in mapping name fails

### ISSUE THREAD

**Issue by bemeyert** [taskrabbit/elasticsearch-dump#132]
```
[root@salttestvm70 elasticdump]# bin/elasticdump --input=http://metrics-sto1:9200/logstash-2015.10.24 --output=http://localhost:9200/logstash-2015.10.24 --type=mapping
Thu, 29 Oct 2015 16:00:25 GMT | starting dump
Thu, 29 Oct 2015 16:00:25 GMT | got 1 objects from source elasticsearch (offset: 0)

Error: failed to parse json (message: "Unexpected token N") - source: "No handler found for uri [/logstash-2015.10.24/application/vnd.openxmlformats-officedocument.spreadsheetml.sheet/_mapping] and method [PUT]"
    at Object.module.exports.parse (/root/node_modules/elasticdump/lib/jsonparser.js:4:20)
    at Request._callback (/root/node_modules/elasticdump/lib/transports/elasticsearch.js:156:56)
    at Request.self.callback (/root/node_modules/elasticdump/node_modules/request/request.js:198:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/root/node_modules/elasticdump/node_modules/request/request.js:1082:10)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/root/node_modules/elasticdump/node_modules/request/request.js:1009:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)
```

ES Version is 1.1.2. Is it me (my Index) or is it a bug?

**Comment by evantahler** [comment]
Hard to say.  Can you try making a simple test case creating objects with names like you have for us to test with?

**Comment by bemeyert** [comment]
@evantahler I'm sorry, but I don't know how to create such a test case. The "slashes" seem to come from the "mappings". Here an excerpt from the index metadata:
```
{

    state: open
    settings: {
        index: {
            uuid: mJ9dJk3KTum0WNo_vp6VgQ
            number_of_replicas: 1
            number_of_shards: 5
            refresh_interval: 5s
            version: {
                created: 1010299
            }
        }
    }
    mappings: {
        image/x-png: {
            dynamic_templates: [
                {
                    string_fields: {
                        mapping: {
                            index: analyzed
                            omit_norms: true
                            type: string
                            fields: {
                                raw: {
                                    index: not_analyzed
                                    ignore_above: 256
                                    type: string
                                }
                            }
                        }
                        match_mapping_type: string
                        match: *
                    }
                }
            ]
            properties: {
                uid: {
                    norms: {
                        enabled: false
                    }
                    type: string
                    fields: {
                        raw: {
                            index: not_analyzed
                            ignore_above: 256
                            type: string
                        }
                    }
                }
                @fields: {
                    type: object
                }
                @message: {
                    norms: {
                        enabled: false
                    }
                    type: string
                    fields: {
                        raw: {
                            index: not_analyzed
                            ignore_above: 256
                            type: string
                        }
                    }
                }
                bytes: {
                    norms: {
                        enabled: false
                    }
                    type: string
                    fields: {
                        raw: {
                            index: not_analyzed
                            ignore_above: 256
                            type: string
                        }
                    }
                }
                @source: {
                    norms: {
                        enabled: false
                    }
                    type: string
                    fields: {
                        raw: {
                            index: not_analyzed
                            ignore_above: 256
                            type: string
                        }
                    }
                }
                status: {
                    norms: {
                        enabled: false
                    }
                    type: string
                    fields: {
                        raw: {
                            index: not_analyzed
                            ignore_above: 256
                            type: string
                        }
                    }
                }
                @type: {
                    norms: {
                        enabled: false
                    }
                    type: string
                    fields: {
                        raw: {
                            index: not_analyzed
                            ignore_above: 256
                            type: string
                        }
                    }
                }
                @source_host: {
                    norms: {
                        enabled: false
                    }
                    type: string
                    fields: {
                        raw: {
                            index: not_analyzed
                            ignore_above: 256
                            type: string
                        }
                    }
                }
                geoip: {
                    dynamic: true
                    properties: {
                        location: {
                            type: geo_point
                        }
                    }
                }
                type: {
                    norms: {
                        enabled: false
                    }
                    type: string
                    fields: {
                        raw: {
                            index: not_analyzed
                            ignore_above: 256
                            type: string
                        }
                    }
                }
                @version: {
                    index: not_analyzed
                    type: string
                }
                url: {
                    norms: {
                        enabled: false
                    }
                    type: string
                    fields: {
                        raw: {
                            index: not_analyzed
                            ignore_above: 256
                            type: string
                        }
                    }
                }
                timestamp: {
                    norms: {
                        enabled: false
                    }
                    type: string
                    fields: {
                        raw: {
                            index: not_analyzed
                            ignore_above: 256
                            type: string
                        }
                    }
                }
                project: {
                    norms: {
                        enabled: false
                    }
                    type: string
                    fields: {
                        raw: {
                            index: not_analyzed
                            ignore_above: 256
                            type: string
                        }
                    }
                }
                @timestamp: {
                    format: dateOptionalTime
                    type: date
                }
                duration: {
                    norms: {
                        enabled: false
                    }
                    type: string
                    fields: {
                        raw: {
                            index: not_analyzed
                            ignore_above: 256
                            type: string
                        }
                    }
                }
                hit: {
                    norms: {
                        enabled: false
                    }
                    type: string
                    fields: {
                        raw: {
                            index: not_analyzed
                            ignore_above: 256
                            type: string
                        }
                    }
                }
                proxy: {
                    norms: {
                        enabled: false
                    }
                    type: string
                    fields: {
                        raw: {
                            index: not_analyzed
                            ignore_above: 256
                            type: string
                        }
                    }
                }
                siteid: {
                    norms: {
                        enabled: false
                    }
                    type: string
                    fields: {
                        raw: {
                            index: not_analyzed
                            ignore_above: 256
                            type: string
                        }
                    }
                }
                method: {
                    norms: {
                        enabled: false
                    }
                    type: string
                    fields: {
                        raw: {
                            index: not_analyzed
                            ignore_above: 256
                            type: string
                        }
                    }
                }
                @source_path: {
                    norms: {
                        enabled: false
                    }
                    type: string
                    fields: {
                        raw: {
                            index: not_analyzed
                            ignore_above: 256
                            type: string
                        }
                    }
                }
                requestid: {
                    norms: {
                        enabled: false
                    }
                    type: string
                    fields: {
                        raw: {
                            index: not_analyzed
                            ignore_above: 256
                            type: string
                        }
                    }
                }
            }
        }
[...]
```

**Comment by bemeyert** [comment]
BTW: I guess escaping the slashes (better any special char) in the URL should do the trick.

**Comment by evantahler** [comment]
Closing due to inactivity.
