### ISSUE TITLE
Input crash for large input from http

### ISSUE THREAD

**Issue by utkarshsins** [taskrabbit/elasticsearch-dump#139]
This error comes up for a large input (10GB+) when reading. 
**node** memory usage keeps going up until crash.

```
$ elasticdump --input=http://127.0.0.1:9200/ --all=true --output=$ | gzip > data.json.gz

buffer.js:194
      this.parent = new SlowBuffer(this.length);
                    ^
RangeError: length > kMaxLength
    at new Buffer (buffer.js:194:21)
    at Function.Buffer.concat (buffer.js:495:16)
    at BufferList.copy (/usr/local/lib/node_modules/elasticdump/node_modules/request/node_modules/bl/bl.js:113:21)
    at BufferList.slice (/usr/local/lib/node_modules/elasticdump/node_modules/request/node_modules/bl/bl.js:88:15)
    at BufferList.toString (/usr/local/lib/node_modules/elasticdump/node_modules/request/node_modules/bl/bl.js:155:15)
    at Request.<anonymous> (/usr/local/lib/node_modules/elasticdump/node_modules/request/request.js:1013:32)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/elasticdump/node_modules/request/request.js:962:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16

```

```
$ elasticdump --input=http://127.0.0.1:9200/ --all=true --output=data.json

buffer.js:194
      this.parent = new SlowBuffer(this.length);
                    ^
RangeError: length > kMaxLength
    at new Buffer (buffer.js:194:21)
    at Function.Buffer.concat (buffer.js:495:16)
    at BufferList.copy (/usr/local/lib/node_modules/elasticdump/node_modules/request/node_modules/bl/bl.js:113:21)
    at BufferList.slice (/usr/local/lib/node_modules/elasticdump/node_modules/request/node_modules/bl/bl.js:88:15)
    at BufferList.toString (/usr/local/lib/node_modules/elasticdump/node_modules/request/node_modules/bl/bl.js:155:15)
    at Request.<anonymous> (/usr/local/lib/node_modules/elasticdump/node_modules/request/request.js:1013:32)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/elasticdump/node_modules/request/request.js:962:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16

```

**Comment by evantahler** [comment]
What version of node are you using?  That error is specifically about "string length", which tends to indicate that you have one *really big* document you might be trying to dump.  That's also why the error's stack comes from within the request (HTTP) module itself, and elaticdump trying to JSON.parse the string or anything like that.

**Comment by utkarshsins** [comment]
For compatibility reasons I was using node 0.10
I have upgraded to node v5.3.0

Is there any easy way to figure out which document is causing this?
````
$ node elasticdump --input=http://127.0.0.1:9200/ --limit=20 --all=true --debug=true --output=~/data.json
Wed, 23 Dec 2015 12:42:33 GMT | starting dump
buffer.js:400
    throw new Error('toString failed');
    ^

Error: toString failed
    at Buffer.toString (buffer.js:400:11)
    at BufferList.toString (/usr/local/lib/node_modules/elasticdump/node_modules/request/node_modules/bl/bl.js:155:33)
    at Request.<anonymous> (/usr/local/lib/node_modules/elasticdump/node_modules/request/request.js:1013:32)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/elasticdump/node_modules/request/request.js:962:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:455:9)
````

**Comment by evantahler** [comment]
Not that I know of.  This would be an issue with the request package.  You probably will need to do some modifications there to get the string as part of the error message.
