### ISSUE TITLE
Error: Cannot switch to old mode now

### ISSUE THREAD

**Issue by canadatom** [taskrabbit/elasticsearch-dump#164]
My json looks like this
```
root@74b2247423e2:/tmp# cat /tmp/kibana.json
{"_index":".kibana","_type":"visualization","_id":"test","_score":0,"_source":{"title":"test","visState":"{\"title\":\"New Visualization\",\"type\":\"pie\",\"params\":{\"shareYAxis\":true,\"addTooltip\":true,\"addLegend\":true,\"isDonut\":false},\"aggs\":[{\"id\":\"1\",\"type\":\"count\",\"schema\":\"metric\",\"params\":{}}],\"listeners\":{}}","uiStateJSON":"{}","description":"","version":1,"kibanaSavedObjectMeta":{"searchSourceJSON":"{\"index\":\"logstash-*\",\"query\":{\"query_string\":{\"query\":\"*\",\"analyze_wildcard\":true}},\"filter\":[]}"}}}
{"_index":".kibana","_type":"visualization","_id":"date-vi","_score":0,"_source":{"title":"date-vi","visState":"{\"title\":\"New Visualization\",\"type\":\"line\",\"params\":{\"shareYAxis\":true,\"addTooltip\":true,\"addLegend\":true,\"showCircles\":true,\"smoothLines\":false,\"interpolate\":\"linear\",\"scale\":\"linear\",\"drawLinesBetweenPoints\":true,\"radiusRatio\":9,\"times\":[],\"addTimeMarker\":false,\"defaultYExtents\":false,\"setYExtents\":false,\"yAxis\":{}},\"aggs\":[{\"id\":\"1\",\"type\":\"count\",\"schema\":\"metric\",\"params\":{}},{\"id\":\"2\",\"type\":\"date_histogram\",\"schema\":\"segment\",\"params\":{\"field\":\"@timestamp\",\"interval\":\"auto\",\"customInterval\":\"2h\",\"min_doc_count\":1,\"extended_bounds\":{}}}],\"listeners\":{}}","uiStateJSON":"{}","description":"","version":1,"kibanaSavedObjectMeta":{"searchSourceJSON":"{\"index\":\"logstash-*\",\"query\":{\"query_string\":{\"query\":\"*\",\"analyze_wildcard\":true}},\"filter\":[]}"}}}
```

Here is the issue
```
root@74b2247423e2:/tmp# elasticdump --input=/tmp/kibana.json --output=http://localhost:9200/.kibana
Tue, 16 Feb 2016 19:13:25 GMT | starting dump

_stream_readable.js:730
    throw new Error('Cannot switch to old mode now.');
          ^
Error: Cannot switch to old mode now.
    at emitDataEvents (_stream_readable.js:730:11)
    at ReadStream.Readable.pause (_stream_readable.js:721:3)
    at file.completeBatch (/usr/local/lib/node_modules/elasticdump/lib/transports/file.js:75:19)
    at Stream.<anonymous> (/usr/local/lib/node_modules/elasticdump/lib/transports/file.js:65:10)
    at Stream.EventEmitter.emit (events.js:117:20)
    at drain (/usr/local/lib/node_modules/elasticdump/node_modules/JSONStream/node_modules/through/index.js:34:23)
    at Stream.stream.queue.stream.push (/usr/local/lib/node_modules/elasticdump/node_modules/JSONStream/node_modules/through/index.js:45:5)
    at Stream.<anonymous> (/usr/local/lib/node_modules/elasticdump/node_modules/JSONStream/index.js:26:12)
    at _end (/usr/local/lib/node_modules/elasticdump/node_modules/JSONStream/node_modules/through/index.js:65:9)
    at Stream.stream.end (/usr/local/lib/node_modules/elasticdump/node_modules/JSONStream/node_modules/through/index.js:74:5)
```

**Comment by evantahler** [comment]
This seems to be a stream issue.  What version of node are you running?

**Comment by canadatom** [comment]
```
root@e3b815d44d03:/# node -v
v0.10.25
```
I am using the Dockerfile provided in the repo to build the image.

**Comment by evantahler** [comment]
Ahh.  The dockerfile is out of date!  
Thanks!

**Comment by canadatom** [comment]
Do you have a recommended node version? I can update it and make a PR.

**Comment by evantahler** [comment]
Give this branch a try: https://github.com/taskrabbit/elasticsearch-dump/pull/165/

**Comment by evantahler** [comment]
closing, moving conversation to https://github.com/taskrabbit/elasticsearch-dump/pull/165

**Comment by jogaco** [comment]
I was just bitten by this, in a fresh elasticsearch-dump installation from today. Is this fixed in 1.0.3? How can I know the version I have?

**Comment by evantahler** [comment]
your node.js version needs to be >= v1.0.0.  `node --version` will let you know which version you are running.

**Comment by jogaco** [comment]
Thanks for the tip.
This is what I did in my Ubuntu server and it seems to work now:

```
sudo npm install -g n
sudo n stable
```
