### ISSUE TITLE
Cannot switch to old mode now

### ISSUE THREAD

**Issue by vananiev** [taskrabbit/elasticsearch-dump#169]
Hello,

I'm tying to restore data from backup json-file.

At first, i restore mapping by
`./elasticdump --input=http://127.0.0.1:9200/source --output=http://127.0.0.1:9200/my_index --type=mapping`

When i run
`./elasticdump --bulk=true --input=/tmp/buckup.json --output=http://12.0.0.1:9200/my_index`

and get

```
_stream_readable.js:749
    throw new Error('Cannot switch to old mode now.');
          ^
Error: Cannot switch to old mode now.
    at emitDataEvents (_stream_readable.js:749:11)
    at ReadStream.Readable.pause (_stream_readable.js:740:3)
    at file.completeBatch (/tmp/npm.rpm/node_modules/elasticdump/lib/transports/file.js:75:19)
    at Stream.<anonymous> (/tmp/npm.rpm/node_modules/elasticdump/lib/transports/file.js:56:12)
    at Stream.emit (events.js:95:17)
    at drain (/tmp/npm.rpm/node_modules/elasticdump/node_modules/JSONStream/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/tmp/npm.rpm/node_modules/elasticdump/node_modules/JSONStream/node_modules/through/index.js:45:5)
    at Parser.parser.onToken (/tmp/npm.rpm/node_modules/elasticdump/node_modules/JSONStream/index.js:91:18)
    at Parser.proto.write (/tmp/npm.rpm/node_modules/elasticdump/node_modules/JSONStream/node_modules/jsonparse/jsonparse.js:96:34)
    at Stream.<anonymous> (/tmp/npm.rpm/node_modules/elasticdump/node_modules/JSONStream/index.js:21:12)
```
If i restore data from source index directly it is ok.

------------

I'm using CentOS-6.7
with nodejs-0.10.42 and nodejs-0.10.36.

**Comment by evantahler** [comment]
related to https://github.com/taskrabbit/elasticsearch-dump/issues/164

**Comment by evantahler** [comment]
you need node.js > `v1.0.0` to use this tool.

**Comment by vananiev** [comment]
thakns, i'll try and write about results

**Comment by regel** [comment]
With RHEL7 you can install the tool with yum -y elasticdump
You might want to upgrade if possible to EL7. Otherwise, downloading the src.rpm and recompiling the RPM using rpmbuild in CentOS6-7 environment can be worth trying out.
