### ISSUE TITLE
Unable to import records with _routing field

### ISSUE THREAD

**Issue by MarcusNoble** [taskrabbit/elasticsearch-dump#210]
Using the latest version on npm I am unable to import records that have a `_routing` field specified.

I am trying to copy data from one index to another.

Example mapping:
```
{
    "mappings": {
        "level0": {
            "properties": {
                "SubjectAreaID": {
                    "type": "long"
                },
                "SubjectAreaName": {
                    "type": "string",
                    "index": "not_analyzed"
                }
            }
        },
        "level1": {
            "_parent": {
                "type": "level0"
            },
            "properties": {
                "SubjectAreaID": {
                    "type": "long"
                },
                "SubjectAreaName": {
                    "type": "string",
                    "index": "not_analyzed"
                }
            }
        },
        "level2": {
            "_parent": {
                "type": "level1"
            },
            "properties": {
                "SubjectAreaID": {
                    "type": "long"
                },
                "SubjectAreaName": {
                    "type": "string",
                    "index": "not_analyzed"
                }
            }
        },
        "level3": {
            "_parent": {
                "type": "level2"
            },
            "properties": {
                "SubjectAreaID": {
                    "type": "long"
                },
                "SubjectAreaName": {
                    "type": "string",
                    "index": "not_analyzed"
                }
            }
        }
    }
}
```

Error thrown by elasticsearch

```
2016-05-11 16:11:42,262][INFO ][rest.suppressed          ] /cats_v1/level3/22801 Params: {index=cats_v1, id=22801, type=level3}
[cats_v1] RoutingMissingException[routing is required for [cats_v1]/[level3]/[22801]]
	at org.elasticsearch.action.index.IndexRequest.process(IndexRequest.java:627)
	at org.elasticsearch.action.index.TransportIndexAction.resolveRequest(TransportIndexAction.java:128)
	at org.elasticsearch.action.index.TransportIndexAction.resolveRequest(TransportIndexAction.java:65)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase.doRun(TransportReplicationAction.java:424)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at org.elasticsearch.action.support.replication.TransportReplicationAction.doExecute(TransportReplicationAction.java:125)
	at org.elasticsearch.action.index.TransportIndexAction.innerExecute(TransportIndexAction.java:134)
	at org.elasticsearch.action.index.TransportIndexAction.doExecute(TransportIndexAction.java:118)
	at org.elasticsearch.action.index.TransportIndexAction.doExecute(TransportIndexAction.java:65)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:70)
	at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:58)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:351)
	at org.elasticsearch.client.FilterClient.doExecute(FilterClient.java:52)
	at org.elasticsearch.rest.BaseRestHandler$HeadersAndContextCopyClient.doExecute(BaseRestHandler.java:83)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:351)
	at org.elasticsearch.client.support.AbstractClient.index(AbstractClient.java:363)
	at org.elasticsearch.rest.action.index.RestIndexAction.handleRequest(RestIndexAction.java:102)
	at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:54)
	at org.elasticsearch.rest.RestController.executeHandler(RestController.java:207)
	at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:166)
	at org.elasticsearch.http.HttpServer.internalDispatchRequest(HttpServer.java:128)
	at org.elasticsearch.http.HttpServer$Dispatcher.dispatchRequest(HttpServer.java:86)
	at org.elasticsearch.http.netty.NettyHttpServerTransport.dispatchRequest(NettyHttpServerTransport.java:363)
	at org.elasticsearch.http.netty.HttpRequestHandler.messageReceived(HttpRequestHandler.java:63)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.http.netty.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:60)
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:75)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by evantahler** [comment]
Can you show an example command you ran to use elasticdump and some example data?

**Comment by MarcusNoble** [comment]
The command I used was

```
elasticdump --input=http://example.com/index1 --output=http://example.com/index2 --type=data
```

This is after creating index2 with the correct mapping.


Sample data:

```

         {
            "_index": "cats",
            "_type": "level0",
            "_id": "21082",
            "_score": 1,
            "_source": {
               "SubjectAreaName": "Agricultural and Biological Sciences",
               "SubjectAreaID": 21082
            }
         },
         {
            "_index": "cats",
            "_type": "level1",
            "_id": "21128",
            "_score": 1,
            "_parent": "21082",
            "_routing": "21082",
            "_source": {
               "SubjectAreaName": "Plant Science",
               "SubjectAreaID": 21128
            }
         },
         {
            "_index": "cats",
            "_type": "level2",
            "_id": "21410",
            "_score": 1,
            "_parent": "21128",
            "_routing": "21082",
            "_source": {
               "SubjectAreaName": "Plant Science",
               "SubjectAreaID": 21410
            }
         },
         {
            "_index": "cats",
            "_type": "level2",
            "_id": "21314",
            "_score": 1,
            "_parent": "21109",
            "_routing": "21066",
            "_source": {
               "SubjectAreaName": "Spectroscopy",
               "SubjectAreaID": 21314
            }
         },
         {
            "_index": "cats",
            "_type": "level3",
            "_id": "21998",
            "_score": 1,
            "_parent": "21410",
            "_routing": "21082",
            "_source": {
               "SubjectAreaName": "Plant Physiology and Biochemistry",
               "SubjectAreaID": 21998
            }
         },
         {
            "_index": "cats",
            "_type": "level3",
            "_id": "21477",
            "_score": 1,
            "_parent": "21312",
            "_routing": "21066",
            "_source": {
               "SubjectAreaName": "Photochemistry",
               "SubjectAreaID": 21477
            }
         }
```

**Comment by evantahler** [comment]
Can you try with the latest version of the tool?

**Comment by MarcusNoble** [comment]
Yes that looks to be working now! Thank you!
