### ISSUE TITLE
SyntaxError: Unexpected token ' 

### ISSUE THREAD

**Issue by melbouhy** [taskrabbit/elasticsearch-dump#244]
Hello,

- ElasticDump version : 2.4.0
- Elasticsearch version: 1.7
- Node version : 4.4.7
- Full command you are having issue with (with inputs and outputs)

elasticdump \  
    --input=http://localhost:9200/.kibana  \
    --output=$ \
    --type=data \
    --searchBody='{"filter": { "or": [ {"type": {"value": "dashboard"}}, {"type" : {"value":"visualization"}}] }}' \
    > kibana-exported.json

I'm trying to do the same tuto as http://air.ghost.io/kibana-4-export-and-import-visualizations-and-dashboards/

When I don't add the searchBody part all goes ok. But when I add it I have the error

SyntaxError: Unexpected token '
    at Object.parse (native)
    at Object.<anonymous> (C:\Users\AppData\Roaming\npm\node_modules\elasticdump\bin\elasticdump:45:23)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

Thank you

**Comment by evantahler** [comment]
I think this is a windows-specific problem.  Use double-quotes everywhere and escape them (`\"`) inside your search body.
