### ISSUE TITLE
get error "RangeError: Invalid string length", then import break off

### ISSUE THREAD

**Issue by showmeall** [taskrabbit/elasticsearch-dump#280]
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version
- Elasticsearch version
- Full command you are having issue with (with inputs and outputs)
- A data set you can share publicly which reproduces the problem

when we import data , get follow error, please help us .

/usr/lib/node_modules/elasticdump/lib/transports/elasticsearch.js:405
    payload.body += JSON.stringify(elem._source) + '\n'
                         ^
RangeError: Invalid string length
    at Object.stringify (native)
    at /usr/lib/node_modules/elasticdump/lib/transports/elasticsearch.js:405:26
    at Array.forEach (native)
    at elasticsearch.setData (/usr/lib/node_modules/elasticdump/lib/transports/elasticsearch.js:380:8)
    at /usr/lib/node_modules/elasticdump/lib/transports/elasticsearch.js:177:12
    at elasticsearch.version (/usr/lib/node_modules/elasticdump/lib/transports/elasticsearch.js:38:32)
    at elasticsearch.set (/usr/lib/node_modules/elasticdump/lib/transports/elasticsearch.js:173:8)
    at /usr/lib/node_modules/elasticdump/elasticdump.js:127:21
    at file.completeBatch (/usr/lib/node_modules/elasticdump/lib/transports/file.js:92:10)
    at Stream.<anonymous> (/usr/lib/node_modules/elasticdump/lib/transports/file.js:60:12)

**Comment by showmeall** [comment]
i found the problem, there have a very long json record ,  i try to use --ignore-errors , but can not skip the error, the import can not countinue.

**Comment by evantahler** [comment]
Sorry, this is a limitation of node.js.... if we can't parse your record because it is too big, there's nothing to be done.
