### ISSUE TITLE
Syntax Error unexpected token <

### ISSUE THREAD

**Issue by gauravlath07** [taskrabbit/elasticsearch-dump#286]
Hi

I am trying to move an elasticsearch index from one server to another and tried this command
elasticdump --input=http://localhost:9200/settings --output=http://xx.xxx.xx.xxx/settings --type=analyzer

and got this error

Wed, 08 Feb 2017 17:43:31 GMT | starting dump
Wed, 08 Feb 2017 17:43:31 GMT | got 1 objects from source elasticsearch (offset: 0)
undefined:1
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
^

SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at Request._callback (/usr/lib/node_modules/elasticdump/lib/transports/elasticsearch.js:43:21)
    at Request.self.callback (/usr/lib/node_modules/elasticdump/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/lib/node_modules/elasticdump/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/elasticdump/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:291:16)

Elasticdump version : 3.1.0
Elasticsearch version : 2.4.1

**Comment by evantahler** [comment]
Look at the reults of that web request (`http://localhost:9200/settings`), I'll bet you are getting back HTML rather than JSON
