### ISSUE TITLE
SyntaxError: Unexpected token <     at Object.parse (native)

### ISSUE THREAD

**Issue by sahas-** [taskrabbit/elasticsearch-dump#289]
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version : version: 3.1.0
- Elasticsearch version : 2.4.1
- Full command you are having issue with (with inputs and outputs)

xyz@dev-elasticsearch-vm:~/node_modules/elasticdump$ ./bin/elasticdump --input="http://localhost/elasticsearch/fuzzy_items" --output="http://localhost/elasticsearch/testmigration" --type=data --debug

Sun, 12 Feb 2017 17:40:45 GMT | starting dump
SyntaxError: Unexpected token <
    at Object.parse (native)
    at Request._callback (/home/xyz/node_modules/elasticdump/lib/transports/elasticsearch.js:43:21)
    at Request.self.callback (/home/xyz/node_modules/elasticdump/node_modules/request/request.js:186:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/home/xyz/node_modules/elasticdump/node_modules/request/request.js:1081:10)
    at Request.emit (events.js:95:17)
    at IncomingMessage.<anonymous> (/home/xyz/node_modules/elasticdump/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:180:16)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:929:16

- A data set you can share publicly which reproduces the problem
regardless of large or small dataset, this is reproducible.

I've the index with data. Elasticsearch is up and running too

xyz@dev-elasticsearch-vm:~/node_modules/elasticdump$ curl localhost/elasticsearch
{
  "name" : "Leila Davis",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "ayRschqVQlGJLpbmX-NPjg",
  "version" : {
    "number" : "2.4.1",
    "build_hash" : "c67dc32e24162035d18d6fe1e952c4cbcbe79d16",
    "build_timestamp" : "2016-09-27T18:57:55Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.2"
  },
  "tagline" : "You Know, for Search"
}

**Comment by jhazelwo-charter** [comment]
Do a `curl` on your input string, for example: `curl http://localhost/elasticsearch/fuzzy_items` if that returns an error then that's the cause of the error message from elasticdump.

**Comment by michalsvec** [comment]
This most likely fails because it makes a request to "http://localhost/" instead of "http://localhost/elasticsearch/". Also if I use input and input-index parameters, the result is still the same.

**Comment by evantahler** [comment]
ref https://github.com/taskrabbit/elasticsearch-dump/issues/301
