### ISSUE TITLE
SyntaxError: Unexpected token q in JSON at position 1

### ISSUE THREAD

**Issue by sujaldalia** [taskrabbit/elasticsearch-dump#303]
ElasticDump version: 3.1.0
Elasticsearch version: 2.3.1

I'm trying to filter the data using --searchBody and getting error

elasticdump --input=http://localhost:9200/frictionless --output=c:/Download/abcd.json --type=
data --searchBody '{"query":{"term":{"PAGE_NAME": "AddressVerificationPage"}}}'

undefined:1
'{query:{term:{PAGE_NAME:
^

SyntaxError: Unexpected token ' in JSON at position 0
    at Object.parse (native)
    at Object.<anonymous> (C:\Users\sdalia200\AppData\Roaming\npm\node_modules\elasticdump\bin\elasticdump:50:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)

**Comment by sxmon** [comment]
#244

**Comment by ferronrsmith** [comment]
Single quotes are not used at all by the cmd.exe command processor except to enclose the command to run within a FOR /F statement:
