### ISSUE TITLE
buffer.js:456 throw new Error('toString failed');

### ISSUE THREAD

**Issue by xiaodin1** [taskrabbit/elasticsearch-dump#336]
In order to help us troubleshoot issues with this project, you **must** provide the following details:
This problem appaer at different offset  in the same index dumping progress, how can i do for that
thx
- ElasticDump version
3.0
- Elasticsearch version
2.3.4
- Full command you are having issue with (with inputs and outputs)
[root@cq02-test01.cq02 bin]# ./elasticdump --input=http://iseces.xx.com:8200/08d84510884d9d91cb71c68ad072b39f-events/ --output=http://iseces.xx.com:8200/xxtest --type=data  --limit=10000 --scrollTime=50m --maxSockets=50 --offset=410010
- A data set you can share publicly which reproduces the problem
Thu, 20 Jul 2017 03:17:26 GMT | starting dump
Thu, 20 Jul 2017 03:17:26 GMT | Warning: offseting 410010 rows.
Thu, 20 Jul 2017 03:17:26 GMT |   * Using an offset doesn't guarantee that the offset rows have already been written, please refer to the HELP text.
buffer.js:456
    throw new Error('toString failed');
    ^

Error: toString failed
    at Buffer.toString (buffer.js:456:11)
    at Request.<anonymous> (/usr/bin/node_modules/elasticdump/node_modules/request/request.js:1145:39)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/bin/node_modules/elasticdump/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:923:12)
    at nextTickCallbackWith2Args (node.js:511:9)
----------------------------------------------------------------------------------------------
Thu, 20 Jul 2017 03:39:03 GMT | sent 15000 objects to destination elasticsearch, wrote 15000
buffer.js:456
    throw new Error('toString failed');
    ^

Error: toString failed
    at Buffer.toString (buffer.js:456:11)
    at Request.<anonymous> (/usr/bin/node_modules/elasticdump/node_modules/request/request.js:1145:39)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/bin/node_modules/elasticdump/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:923:12)
    at nextTickCallbackWith2Args (node.js:511:9)

**Comment by ferronrsmith** [comment]
Issue hasn't been updated in months. Closing
Please re-open if you do not feel the question has been answered sufficiently.
