### ISSUE TITLE
SyntaxError: Unexpected token =>

### ISSUE THREAD

**Issue by GITburakdeniz** [taskrabbit/elasticsearch-dump#349]
- ElasticDump version :  3.3.1
- Elasticsearch version :  1.7.3
Full command;

elasticdump \
  --input=http://localhost:9200/mean \
  --output=/home/user/ElasticExportedData/elastic_mean_data.json \
  --type=data

/home/user/.nvm/versions/node/v0.12.17/lib/node_modules/elasticdump/elasticdump.js:18
    .reduce((params, param) => {
                            ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/user/.nvm/versions/node/v0.12.17/lib/node_modules/elasticdump/bin/elasticdump:5:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

**Comment by evantahler** [comment]
Elsaticdump requires node v4 or higher (codified [here](https://github.com/taskrabbit/elasticsearch-dump/blob/master/package.json#L27)).  You are using v0.12.   NPM should have warned you of this when in  installed the project.
