### ISSUE TITLE
Multielasticdump fail to complete triggered from cronjob

### ISSUE THREAD

**Issue by nicomagliaro** [taskrabbit/elasticsearch-dump#356]
[elasticsearch.sh.zip](https://github.com/taskrabbit/elasticsearch-dump/files/1467878/elasticsearch.sh.zip)

- ElasticDump **3.3.1**
- Elasticsearch **1.4.4**
- Command: **/usr/local/bin/multielasticdump --direction=dump --input=http://172.16.106.32:9200/ --output=/share/tbx/elastic-HUB2/**
- We're trying to dump remote elasticsearch through a LAN tcp connection. We're setting up a cronjob script:
30 2 */2 * * /bin/bash -c "/share/tbx/elastic-HUB2/elasticdump.sh" > /share/tbx/elastic-HUB2/output.log 2>&1
output: 
`+ set -e
+ NAME=elastic-HUB2
++ /bin/date +%Y-%m-%d
+ DSTRING=2017-11-13
+ ARCHSTRING=elastic-HUB2.2017-11-13
+ CRON=backup.elastic-HUB2.2017-11-13
+ LOCKFILE=/tmp/cron.backup.elastic-HUB2.2017-11-13.lock
+ BACKUP_HOME=/share/tbx/elastic-HUB2
+ BACKUP_DIR=/share/tbx/elastic-HUB2/2017-11-13
+ LOG_DIR=/share/tbx/elastic-HUB2/error.log
+ RETENTION_DAYS=15
+ TMP_DIR=/share/tbx/elastic-HUB2/2017-11-13/tmp
+ CURRENT_DIR=/share/tbx
+ trap quit INT TERM EXIT
+ '[' -f /tmp/cron.backup.elastic-HUB2.2017-11-13.lock ']'
+ touch /tmp/cron.backup.elastic-HUB2.2017-11-13.lock
+ rm -rf /share/tbx/elastic-HUB2/2017-11-13
+ mkdir -p /share/tbx/elastic-HUB2/2017-11-13/tmp
+ /usr/local/bin/multielasticdump --direction=dump --input=http://172.16.106.32:9200/ --output=/share/tbx/elastic-HUB2/2017-11-13/tmp/
Mon, 13 Nov 2017 05:30:03 GMT | We are performing : dump
Mon, 13 Nov 2017 05:30:03 GMT | options: {"debug":true,"parallel":8,"match":"^.*$","input":"http://172.16.106.32:9200/","output":"/share/tbx/elastic-HUB2/2017-11-13/tmp/","scrollTime":"10m","limit":100,"offset":0,"direction":"dump"}
Mon, 13 Nov 2017 05:30:03 GMT | dumping http://172.16.106.32:9200//59259bec5a1ba865cc3389c0 to /share/tbx/elastic-HUB2/2017-11-13/tmp//59259bec5a1ba865cc3389c0.mapping.json
Mon, 13 Nov 2017 05:30:04 GMT | dumping http://172.16.106.32:9200//57a1fe057beaec6e57fdf2e2 to /share/tbx/elastic-HUB2/2017-11-13/tmp//57a1fe057beaec6e57fdf2e2.mapping.json

/usr/local/lib/node_modules/elasticdump/lib/transports/elasticsearch.js:16
    headers: Object.assign({
                    ^
TypeError: Object function Object() { [native code] } has no method 'assign'
    at new elasticsearch (/usr/local/lib/node_modules/elasticdump/lib/transports/elasticsearch.js:16:21)
    at new elasticdump (/usr/local/lib/node_modules/elasticdump/elasticdump.js:61:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/elasticdump/bin/elasticdump:83:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
Mon, 13 Nov 2017 05:30:04 GMT | Error: CHILD PROCESS EXITED WITH ERROR.  Stopping process
+ quit
+ echo 1
+ rm -rf /tmp/cron.backup.elastic-HUB2.2017-11-13.lock
+ exit
`

Every time I run the exact same command manually from bash, it completed with no error whatsoever!

**Comment by nicomagliaro** [comment]
That was my first tought (kind of versions uncompatibility), but then running manually and worked out was confusing.
Really don't know what's going on under the hood when run bash command.

> node version output:
`node --version
v4.4.5
`

**Comment by nicomagliaro** [comment]
Finally i fixed the issue by starting my command like this:

/usr/bin/n use {node version} /usr/local/bin/multielasticdump --direction=dump --input={url} --output={path}
