### ISSUE TITLE
can't backup data with elaistcdump output error

### ISSUE THREAD

**Issue by zqc0512** [taskrabbit/elasticsearch-dump#358]
[root@test elasticdump]# elasticdump --input=http://xx.xx.xx.xx:9200/.kibana   --output=/opt/elasticdump/kibana.json --type=data
Thu, 16 Nov 2017 02:44:10 GMT | starting dump
undefined:1
<HTML><HEAD>
^

SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at Request._callback (/usr/lib/node_modules/elasticdump/lib/transports/elasticsearch.js:52:21)
    at Request.self.callback (/usr/lib/node_modules/elasticdump/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/lib/node_modules/elasticdump/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/elasticdump/node_modules/request/request.js:1085:12)
    at IncomingMessage.g (events.js:292:16)
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version 3.3.1
- Elasticsearch version 5.6.3 
- Full command you are having issue with (with inputs and outputs)
- A data set you can share publicly which reproduces the problem
@jenkins-taskrabbit

**Comment by ferronrsmith** [comment]
try using `--headers='{"Content-Type": "application/json"}'`

**Comment by ferronrsmith** [comment]
Please re-open if you do not feel the question has been answered sufficiently.
