### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by laurazh** [taskrabbit/elasticsearch-dump#387]
- ElasticDump version v.3.x
- Node.js version v8.9.3

-  command  
`elasticdump \`
 ` --input=https://myproduction.es.com:9200/my_index \`
 ` --output=my_index.json \`
  `--searchBody '{  "query":{"range":{"@timestamp":{"gte": 1513342800000,"lte": 1513350000000} }}}'`

-  command  output

> undefined:1
\<html>
^
> SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (C:\Users\AppData\Roaming\npm\node_modules\elasticdump\lib\tra                     nsports\elasticsearch.js:52:21)
    at Request.self.callback (C:\Users\AppData\Roaming\npm\node_modules\elasticdump\nod                     e_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\AppData\Roaming\npm\node_modules\elasticdump\node_                     modules\request\request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\AppData\Roaming\npm\node_modules\elasticdu                     mp\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)

I used to run similar query with no problem.

**Comment by ferronrsmith** [comment]
1. What version of ElasticDump are using ?
1. What's version of Elasticsearch are using ?
1. A data set you can share publicly which reproduces the problem


The issue template is there to help diagnose and replicate your issue.

**Comment by ferronrsmith** [comment]
Closing this issue.
Please re-open if you are still having issues.
