### ISSUE TITLE
Unexpected identifier

### ISSUE THREAD

**Issue by nzolt** [taskrabbit/elasticsearch-dump#409]
/root/node_modules/elasticdump/bin/elasticdump:55
for (var i of jsonParsedOpts) {
           ^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

nodejs v0.10.25

**Comment by ferronrsmith** [comment]
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version
- Elasticsearch version
- Node.js version
- Full command you are having issue with (with inputs and outputs)
- A data set you can share publicly which reproduces the problem
