### ISSUE TITLE
can't copy an index from production to staging with mappings with elasticdump output error

### ISSUE THREAD

**Issue by fnoboa** [taskrabbit/elasticsearch-dump#444]
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version: 3.3.14
- Elasticsearch version:  6.2.3
- Node.js version: 8.9.4
- Full command you are having issue with (with inputs and outputs)

elasticdump --input=http://ip_machine:9200/fersquery --output=http://ip_server:9200/fersquery --type=mapping

Thu, 07 Jun 2018 14:11:36 GMT | starting dump
undefined:1
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (C:\Users\AppData\Roaming\npm\node_modules\elasticdump\lib\transports\elasticse
arch.js:57:21)
    at Request.self.callback (C:\Users\AppData\Roaming\npm\node_modules\elasticdump\node_modules\request
\request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\AppData\Roaming\npm\node_modules\elasticdump\node_modules\request\r
equest.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\AppData\Roaming\npm\node_modules\elasticdump\node_modules\r
equest\request.js:1079:12)
    at Object.onceWrapper (events.js:313:30)

**Comment by ferronrsmith** [comment]
Closing this issue.
Please re-open if you do not feel the question has been answered sufficiently.
