### ISSUE TITLE
Not able to push elasticsearch dump file to localhost

### ISSUE THREAD

**Issue by ihsanhaikalz** [taskrabbit/elasticsearch-dump#460]
I am having a problem to read a dump file from elasticsearch in another system and push it to my elasticsearch using Logstash via file input plugin. My dump file looks like this:

```
    {"_index":"logstash-2018.06.14","_type":"doc","_id":"9Q-9AGQBaaf188t_6DmH","_score":1,"_source":{"offset":124076,"tags":["filebeat_json","beats_input_raw_event","_jsonparsefailure"]...}
    {"_index":"logstash-2018.06.14","_type":"doc","_id":"DQ-9AGQBaaf188t_6DqH","_score":1,"_source":{"offset":145573,"tags":["filebeat_json","beats_input_raw_event","_jsonparsefailure"],...}
```

What I want to do is to use the elasticsearch metadata like _index and push it to my elasticsearch. After a suggestion I found elasticdump and already install it alongside with nodejs. Now I am trying to push it with the command as follow: 

> elasticdump --input=./logstash.json --output=http://localhost:9200/ 

but it gave error like this:

/usr/local/lib/node_modules/elasticdump/lib/transports/elasticsearch.js:668
    var {awsChain, awsAccessKeyId, awsIniFileProfile} = self.parent.options
        ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at getIo (/usr/local/lib/node_modules/elasticdump/lib/ioHelper.js:29:18)
    at new elasticdump (/usr/local/lib/node_modules/elasticdump/elasticdump.js:44:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/elasticdump/bin/elasticdump:96:16)

Any idea why and how to solve it? 
- ElasticDump version 3.3.18
- Elasticsearch version 6.2.4
- Node.js version *(note that nodejs v8+ is required for this tool)* v4.2.6

**Comment by ferronrsmith** [comment]
note that nodejs v8+ is required for this too
