### ISSUE TITLE
json parse error for headers

### ISSUE THREAD

**Issue by johnmahui1** [taskrabbit/elasticsearch-dump#482]
--headers='{"Authorization": "*****"}'

undefined:1
'{Authorization:
^

SyntaxError: Unexpected token ' in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (D:\Users\hui_ma\AppData\Roaming\npm\node_modules\elasticdump\bin\elasticdump:66:39)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

**Comment by johnmahui1** [comment]
that's in windows console, it does work in centos, thanks
