### ISSUE TITLE
How to ignore exist file?

### ISSUE THREAD

**Issue by esgi-dendyanri** [taskrabbit/elasticsearch-dump#513]
Hi,

i use latest version of elasticdump 4.2.0, i try to dump my mapping from file to my elasticsearch.
```
elasticdump --input=./demo_elastic_mapping_20190110.json --output=localhost:9200 --type=mapping
```
the first one was success, but i found wrong mapping.
so i edit the file, **remove all indices**, and run elasticdump again.
i got this:
```
/usr/lib/node_modules/elasticdump/bin/elasticdump:115
    throw new Error('File `' + options.output + '` already exists, quitting')
    ^

Error: File `localhost:9200` already exists, quitting
    at Object.<anonymous> (/usr/lib/node_modules/elasticdump/bin/elasticdump:115:11)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

i believe this is for safety purpose, but how do i ignore this check?
Thanks in advance

**Comment by ferronrsmith** [comment]
It’s very important that you read the documentation. Output should be a valid URL.

```
elasticdump --input=./demo_elastic_mapping_20190110.json --output=http://localhost:9200 --type=mapping
```
