### ISSUE TITLE
support bigint 

### ISSUE THREAD

**Issue by TankistKharkiv** [taskrabbit/elasticsearch-dump#528]
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump 4.6.0
- Elasticsearch 2.4, 5.5.6
- Node.js version 10.4 

command
elasticdump \
  --input="$OLD_URL/$PREFIX$index" \
  --output="$NEW_URL/$PREFIX$index" \
  --awsAccessKeyId=$AWS_KEY_ID \
  --awsSecretAccessKey=$AWS_KEY_SECRET \
  --type=data \
  --limit=1000 \
  --support-big-int

1) we have error on parsing strings like '+123456789123456789', looks like it is required to add extra check like this 
`/^\d+$/.test(value)`
 to lib/jsonparser.js:13

2) Also I still have problem with support bigint
looks like not all jsonParser.parse function calls have config as the second argument, where appropriate (my issue has been fixed throw replace _.get(configs, 'options.support-big-int') with true in line 25, same file)

**Comment by ferronrsmith** [comment]
1. Are you saying you don't want '+123456789123456789' to be detected has a BigInteger. **This seems like an additional constraint that is needed for your data.** 
1. Valid issue ✅

**Comment by TankistKharkiv** [comment]
> 1. Are you saying you don't want '+123456789123456789' to be detected has a BigInteger. **This seems like an additional constraint that is needed for your data.**

but I have error:

```
Error: Invalid number (value: "+123456789123456789")
    at r (/home/dmaltsev/.nvm/versions/node/v8.12.0/lib/node_modules/elasticdump/node_modules/lossless-json/dist/lossless-json.js:1:1097)
    at new r (/home/dmaltsev/.nvm/versions/node/v8.12.0/lib/node_modules/elasticdump/node_modules/lossless-json/dist/lossless-json.js:1:1422)
    at Object._replacer (/home/dmaltsev/.nvm/versions/node/v8.12.0/lib/node_modules/elasticdump/lib/jsonparser.js:26:12)
    at D (/home/dmaltsev/.nvm/versions/node/v8.12.0/lib/node_modules/elasticdump/node_modules/lossless-json/dist/lossless-json.js:1:6660)
    at C (/home/dmaltsev/.nvm/versions/node/v8.12.0/lib/node_modules/elasticdump/node_modules/lossless-json/dist/lossless-json.js:1:6412)
    at D (/home/dmaltsev/.nvm/versions/node/v8.12.0/lib/node_modules/elasticdump/node_modules/lossless-json/dist/lossless-json.js:1:6753)
    at C (/home/dmaltsev/.nvm/versions/node/v8.12.0/lib/node_modules/elasticdump/node_modules/lossless-json/dist/lossless-json.js:1:6412)
    at D (/home/dmaltsev/.nvm/versions/node/v8.12.0/lib/node_modules/elasticdump/node_modules/lossless-json/dist/lossless-json.js:1:6753)
    at C (/home/dmaltsev/.nvm/versions/node/v8.12.0/lib/node_modules/elasticdump/node_modules/lossless-json/dist/lossless-json.js:1:6412)
    at Object.U [as stringify] (/home/dmaltsev/.nvm/versions/node/v8.12.0/lib/node_modules/elasticdump/node_modules/lossless-json/dist/lossless-json.js:1:5763)

```

**Comment by ferronrsmith** [comment]
Push a PR for this. I'll merge + release after the build passes

**Comment by ferronrsmith** [comment]
Get latest
