### ISSUE TITLE
the version that I get just now  don`t work

### ISSUE THREAD

**Issue by wkcaeser** [taskrabbit/elasticsearch-dump#558]
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version  i don`t know
- Elasticsearch version  2.4.6
- Node.js version *(note that nodejs v8+ is required for this tool)*    v6.16.0
- Full command you are having issue with (with inputs and outputs)  
``` shell
       node --max-old-space-size=2048 /usr/bin/elasticdump \
  --input=http://192.168.3.20:9200/tiku_20181015 \
  --type=data \
  --output=http://192.168.5.21:9200 \
  --limit=20000 \
  --noRefresh
```
- A data set you can share publicly which reproduces the problem
``` shell
/usr/lib/node_modules/elasticdump/elasticdump.js:124
  async _loop (limit, offset, totalWrites) {
        ^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/elasticdump/bin/elasticdump:6:21)
```

**Comment by ferronrsmith** [comment]
We don't support node v6. You need to upgrade to v8 or later.
