### ISSUE TITLE
Ineffective mark-compacts near heap limit Allocation failed

### ISSUE THREAD

**Issue by slayer** [taskrabbit/elasticsearch-dump#561]
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump: latest docker image
- Elasticsearch: 7.1.1
- Node.js version: latest docker image

```
/ #   elasticdump \
>   --input=http://es01:9200/filebeat-2019.06.24 \
>   --output=$ \
>   | bzip2 > /index.json.bz2
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory                                                                                      
Aborted (core dumped)
```

```
host # free
              total        used        free      shared     buffers       cache   available
Mem:            39G         34G        375M        2,6M        185M        4,0G        3,9G
Swap:          4,0G        7,8M        4,0G
```

**Comment by slayer** [comment]
Strange. It works well with `gzip`. Do you have ideas why?

**Comment by ferronrsmith** [comment]
bzip technically is a "better" compression algorithm than gzip, but the trade of is speed and performance. it uses more memory than gzip. You can try segmenting the data using the `filesize` param or just sticking with `gzip`.

This isn't really an `elasticdump` issue. Also it doesn't seem back-pressure is being handled properly by bzip. This could be the size of the file it's streaming to + bzip computations. Hard to say really, I mostly use `gzip`, it's ubiquitos

**Comment by ferronrsmith** [comment]
You can also look at #556 and set the

`NODE_OPTIONS="--max-old-space-size=8192"` environment var, to increase the amount of memory allocated to node.

**Comment by slayer** [comment]
It does not work either 
```
/ # NODE_OPTIONS="--max-old-space-size=8192" elasticdump --input=http://es01:9200/filebeat-2019.06.24 --output=$  | bzip2 > /index.json.bz2                   
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: write ENOBUFS
    at afterWriteDispatched (internal/stream_base_commons.js:78:25)
    at writevGeneric (internal/stream_base_commons.js:67:3)
    at Socket._writeGeneric (net.js:711:5)
    at Socket._writev (net.js:720:8)
    at doWrite (_stream_writable.js:413:12)
    at clearBuffer (_stream_writable.js:522:5)
    at onwrite (_stream_writable.js:470:7)
    at WriteWrap.afterWrite [as oncomplete] (net.js:800:19)
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:430:5)
    at onwrite (_stream_writable.js:461:5)
    at _destroy (internal/streams/destroy.js:49:7)
    at Socket.dummyDestroy [as _destroy] (internal/process/stdio.js:11:34)
    at Socket.destroy (internal/streams/destroy.js:37:8)
    at afterWriteDispatched (internal/stream_base_commons.js:78:17)
    at writevGeneric (internal/stream_base_commons.js:67:3)
    at Socket._writeGeneric (net.js:711:5)
    at Socket._writev (net.js:720:8)
```

Looks like bzip2 is slower than gzip and `elasticdump`  has no buffer for to keep output data for slow `bzip2`

**Comment by ferronrsmith** [comment]
**ENOBUFS** means the system buffer has been smashed. You can try segmenting the data using the `fileSize` param. How large is the index you're trying to dump?
