### ISSUE TITLE
[BUG] Dumping and loading data does not work on Elasticsearch 7.3.1

### ISSUE THREAD

**Issue by mihai1voicescu** [taskrabbit/elasticsearch-dump#592]
**Context**
- ElasticDump version 6.8.1
- Elasticsearch version 7.3.1
- Node.js version v12.4.0
- Full command `elasticdump --output=http://localhost:9200/comment --input=./dump/comment-mapping.dump.json --type=mapping`
- A data-set you can share publicly which reproduces the problem

comment-mapping.dump.json:

```
{"comment":{"mappings":{"properties":{"created":{"type":"date"},"creator":{"properties":{"id":{"type":"keyword"},"type":{"type":"keyword"}}},"joinField":{"type":"join","eager_global_ordinals":true,"relations":{"comment":"reply"}},"patientId":{"type":"keyword"},"text":{"type":"text"},"type":{"type":"keyword"}}}}}
```

Log:
```
Mon, 09 Sep 2019 13:05:20 GMT | Error Emitted => {"root_cause":[{"type":"illegal_argument_exception","reason":"Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."}],"type":"illegal_argument_exception","reason":"Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."}
child_process.js:655
    throw err;
    ^

Error: Command failed: elasticdump --output=http://localhost:9200/comment --input=./dump/comment-mapping.dump.json --type=mapping
Mon, 09 Sep 2019 13:05:20 GMT | Error Emitted => {"root_cause":[{"type":"illegal_argument_exception","reason":"Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."}],"type":"illegal_argument_exception","reason":"Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."}

    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at Object.<anonymous> (/Users/mihaivo/PhpstormProjects/medx-backend/setup/es/load.js:12:12)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11 {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer 4d 6f 6e 2c 20 30 39 20 53 65 70 20 32 30 31 39 20 31 33 3a 30 35 3a 32 30 20 47 4d 54 20 7c 20 73 74 61 72 74 69 6e 67 20 64 75 6d 70 0a 4d 6f 6e 2c ... 205 more bytes>,
    <Buffer 4d 6f 6e 2c 20 30 39 20 53 65 70 20 32 30 31 39 20 31 33 3a 30 35 3a 32 30 20 47 4d 54 20 7c 20 45 72 72 6f 72 20 45 6d 69 74 74 65 64 20 3d 3e 20 7b ... 322 more bytes>
  ],
  pid: 71274,
  stdout: <Buffer 4d 6f 6e 2c 20 30 39 20 53 65 70 20 32 30 31 39 20 31 33 3a 30 35 3a 32 30 20 47 4d 54 20 7c 20 73 74 61 72 74 69 6e 67 20 64 75 6d 70 0a 4d 6f 6e 2c ... 205 more bytes>,
  stderr: <Buffer 4d 6f 6e 2c 20 30 39 20 53 65 70 20 32 30 31 39 20 31 33 3a 30 35 3a 32 30 20 47 4d 54 20 7c 20 45 72 72 6f 72 20 45 6d 69 74 74 65 64 20 3d 3e 20 7b ... 322 more bytes>
}
```

**Describe the bug**
Dumping and loading the mappings does not seem to work in 7.3.1

**Comment by ferronrsmith** [comment]
Can't on 7.3.0 & 7.3.1 and I wasn't able to reproduce the issue.

**Comment by mihai1voicescu** [comment]
"Can't on 7.3.0 & 7.3.1" can't install those version of ES or can't reproduce the bug on them?

**Comment by ferronrsmith** [comment]
I was unable to reproduce the issue.

**Comment by mihai1voicescu** [comment]
If I provide docker images which will replicate the issue will it help?

**Comment by ferronrsmith** [comment]
You can provide the version of elasticdump used

**Comment by mihai1voicescu** [comment]
It's in the ticket `ElasticDump version 6.8.1`

**Comment by ferronrsmith** [comment]
As I've said, I'm unable to reproduce the issue.

**Comment by mihai1voicescu** [comment]
Funny enough this seems to work when I try it from Windows, but fails on my mac, although I am using the exact same docker command.

What OS are you testing on?

**Comment by ferronrsmith** [comment]
All my tests were on linux, don't do much development on my Mac, since docker is a bit handicapped.

**Comment by ferronrsmith** [comment]
I tested on Docker MacOS and it works for me.


<img width="728" alt="Screenshot 2019-09-10 at 6 37 45 PM" src="https://user-images.githubusercontent.com/159764/64655379-176fd300-d3fa-11e9-92c0-da640588849a.png">

**Comment by ambs** [comment]
Curiously I am having the same warning. Running 8.3.3, and loading a mapping exported from a 6.x
I do not have this issue when importing on the same version.
Not using docker (local ES installation).

**Comment by ambs** [comment]
This helped: https://stackoverflow.com/questions/58824489/where-to-put-include-type-name-in-config-exs
