### ISSUE TITLE
SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by leiganglee** [taskrabbit/elasticsearch-dump#634]
[root@elasticsearch elasticdump]# ./bin/elasticdump help
/data/esdump/node_modules/elasticdump/lib/processor.js:40
  async _loop (limit, offset, totalWrites) {
        ^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)

how to fix this ?

**Comment by ferronrsmith** [comment]
use a supported version of node. v8 or higher
