### ISSUE TITLE
Invalid argument when trying to upload dump to Google Storage

### ISSUE THREAD

**Issue by SimonLinder** [taskrabbit/elasticsearch-dump#641]
I'm trying to upload the ES dump to Google Cloud Storage and get an InvalidAgrument-Exception.
Here is what I'm trying to call:
`elasticdump --type=data --limit=10000 --input=http://localhost:9200/my_index --s3Endpoint=https://storage.googleapis.com --s3AccessKeyId "my-access-key" --s3SecretAccessKey "my-secret" --output "s3://my-bucket-name/my_index.json"`

And here is what I get:
InvalidArgument: Invalid argument.
    at Request.extractError (/usr/local/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/services/s3.js:585:35)
    at Request.callListeners (/usr/local/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/local/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/usr/local/lib/node_modules/elasticdump/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  message: 'Invalid argument.',
  code: 'InvalidArgument',
  region: null,
  time: 2019-11-20T12:36:02.143Z,
  requestId: null,
  extendedRequestId: undefined,
  cfId: undefined,
  statusCode: 400,
  retryable: false,
  retryDelay: 24.982138449316693
}

The key and secret is all set correctly, if tempering them, I get an unauthorized. Looks like it has something to do with the `output`.

Is there something wrong with my request?

**Comment by ferronrsmith** [comment]
We don't support GCS

**Comment by CousinJohn140** [comment]
Is there a plan to add GCS support?

**Comment by ferronrsmith** [comment]
Simple answer, no. The core will remain as lite as possible. It's fairly easy to write your own transport.
