### ISSUE TITLE
v8 engine buffer size limit

### ISSUE THREAD

**Issue by yueyangtian** [taskrabbit/elasticsearch-dump#644]
- ElasticDump 
   version 4.6.0
- Elasticsearch 
   version 6.3.0
- Node.js version
   6.9.0

Fri, 29 Nov 2019 08:11:15 GMT | sent 100 objects to destination file, wrote 100
buffer.js:495
    throw new Error('"toString()" failed');
    ^

Error: "toString()" failed
    at Buffer.toString (buffer.js:495:11)
    at Request.<anonymous> (/usr/lib/node_modules/elasticdump/node_modules/request/request.js:1135:39)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/elasticdump/node_modules/request/request.js:1083:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:978:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
- A data-set you can share publicly which reproduces the problem

v8 release not support buffer large size just 256M

I want have any skill run it expect complex v8 engine

**Comment by ferronrsmith** [comment]
nove v8 or higher
