### ISSUE TITLE
[FEATURE REQUEST] Dynamic settings are not preserved upon mapping import

### ISSUE THREAD

**Issue by danhooper** [taskrabbit/elasticsearch-dump#667]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version elasticdump 6.20.1
- Elasticsearch version: 7.5.2
- Node.js version 10.16
- Full command you are having issue with (with inputs and outputs)
`elasticdump --input=./not_working.json --output=http://<elastic>:9200/test --type=mapping`
- A data-set you can share publicly which reproduces the problem

not_working.json

`{"test":{"mappings":{"dynamic":false,"properties":{"foo":{"type":"keyword"}}}}}`

**Describe the bug**
When a mapping JSON contains dynamic: false then the setting is not preserved. Also elasticsearch errors with the following stack trace:

```
{"type": "server", "timestamp": "2020-02-11T15:56:18,286Z", "level": "DEBUG", "component": "o.e.a.a.i.m.p.TransportPutMappingAction", "cluster.name": "docker-cluster", "node.name": "d7a79a0eab97", "message": "failed to put mappings on indices [[[test/13FRqKPlR1mk9PlyliFzaw]]], type [_doc]", "cluster.uuid": "UzaGPG_fSAmAwL9Tqh6FJA", "node.id": "cvCh5PmfTzisUc4zyNMgbw" ,
"stacktrace": ["org.elasticsearch.ElasticsearchParseException: properties must be a map type",
"at org.elasticsearch.index.mapper.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:194) ~[elasticsearch-7.5.2.jar:7.5.2]",
"at org.elasticsearch.index.mapper.RootObjectMapper$TypeParser.parse(RootObjectMapper.java:130) ~[elasticsearch-7.5.2.jar:7.5.2]",
"at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:108) ~[elasticsearch-7.5.2.jar:7.5.2]",
"at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:88) ~[elasticsearch-7.5.2.jar:7.5.2]",
"at org.elasticsearch.index.mapper.MapperService.parse(MapperService.java:661) ~[elasticsearch-7.5.2.jar:7.5.2]",
"at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:279) ~[elasticsearch-7.5.2.jar:7.5.2]",
"at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:238) ~[elasticsearch-7.5.2.jar:7.5.2]",
"at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:702) ~[elasticsearch-7.5.2.jar:7.5.2]",
"at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:324) ~[elasticsearch-7.5.2.jar:7.5.2]",
"at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:219) [elasticsearch-7.5.2.jar:7.5.2]",
"at org.elasticsearch.cluster.service.MasterService.access$000(MasterService.java:73) [elasticsearch-7.5.2.jar:7.5.2]",
"at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:151) [elasticsearch-7.5.2.jar:7.5.2]",
"at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) [elasticsearch-7.5.2.jar:7.5.2]",
"at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) [elasticsearch-7.5.2.jar:7.5.2]",
"at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:703) [elasticsearch-7.5.2.jar:7.5.2]",
"at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) [elasticsearch-7.5.2.jar:7.5.2]",
"at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) [elasticsearch-7.5.2.jar:7.5.2]",
"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]",
"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]",
"at java.lang.Thread.run(Thread.java:830) [?:?]"] }
```

The command outputs:
```
Tue, 11 Feb 2020 16:03:23 GMT | starting dump
Tue, 11 Feb 2020 16:03:23 GMT | got 1 objects from source file (offset: 0)
Tue, 11 Feb 2020 16:03:23 GMT | sent 1 objects to destination elasticsearch, wrote 2
Tue, 11 Feb 2020 16:03:23 GMT | got 0 objects from source file (offset: 1)
Tue, 11 Feb 2020 16:03:23 GMT | Total Writes: 2
Tue, 11 Feb 2020 16:03:23 GMT | dump complete
```

After running the command the index mapping is:
```

curl <elastic>:9200/test/_mapping
{"test":{"mappings":{"properties":{"foo":{"type":"keyword"}}}}}
```

**To Reproduce**
1. Create input file with contents above.
2. Run command.

**Current behavior**
Dynamic property is not in the mapping after running this command.

**Expected behavior**
The dynamic properties should be preserved.

**Comment by ferronrsmith** [comment]
this isn't a bug, this feature wasn't supported.
