### ISSUE TITLE
quotes are disappearing from searchBody (PowerShell)

### ISSUE THREAD

**Issue by vorou** [taskrabbit/elasticsearch-dump#94]
I'm sure it's more related to PowerShell, but just in case you know the solution.

```
> elasticdump --input=http://gofra2:9200/gofra/notifications --output=test.json --searchBody '{"query":{"term":{"username": "admin"}}}'
undefined:1
{query:{term:{username: admin}}}
 ^
SyntaxError: Unexpected token q
    at Object.parse (native)
    at Object.<anonymous> (C:\Users\vorou\AppData\Roaming\npm\node_modules\elasticdump\bin\elasticdump:40:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

As you can see there is no quotes in the error message, and so JSON parsing fails.

Now, without quotes:

```
> elasticdump --input=http://gofra2:9200/gofra/notifications --output=test.json --searchBody {"query":{"term":{"username": "admin"}}}
Unexpected token ':' in expression or statement.
```

And with double quotes:

```
> elasticdump --input=http://gofra2:9200/gofra/notifications --output=test.json --searchBody "{"query":{"term":{"username": "admin"}}}"
undefined:1
{

SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Object.<anonymous> (C:\Users\vorou\AppData\Roaming\npm\node_modules\elasticdump\bin\elasticdump:40:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

So much love for PowerShell. Any ideas?

**Comment by evantahler** [comment]
I'm actually happy to see the tool works on windows at all! (I didn't expect that it would).

Anyone else here have a windows computer (I don't) and the ability to test this out?  I would guess that the proper way to escape this would be something like:

```
elasticdump --input=http://gofra2:9200/gofra/notifications --output=test.json --searchBody "{\"query\":{\"term\":{\"username\": \"admin\"}}}"
```

**Comment by vorou** [comment]
Yay, it's working!

It's only you need single quotes, not double, like this:

```
elasticdump --input=http://gofra2:9200/gofra/notifications --output=test.json --searchBody '{\"query\":{\"term\":{\"username\": \"admin\"}}}'
```

Thanks for the answer (and a great tool)! I guess you can close the issue.
